### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by imcotton** [imcotton/ngx-endpoint#26]
- [ ] Up to Angular **6+**
- [x] CI / CD migrate from **CircleCI** to **GitHub Actions** (new)
- [x] **Codecov** for coverage
